import Head from 'next/head'
import Image from 'next/image'
import formImage from '../public/form.png';
import {useFormik} from 'formik';
import * as Yup from 'yup';
import Router, { useRouter } from 'next/router';


export default function Home() {
  
  const router = useRouter();

  //formic logics
  
  const formik = useFormik({
    initialValues: {
      name: "",
      email: "",
      country: 'India',
      terms: "",
    },

  //validation
   validationSchema: Yup.object({
    name: Yup.string()
    .max(20, 'Name must be 20 characters or less.')
    .required("Name is required"),

    email: Yup.string()
    .email('Invalid email address.')
    .required("Email is required"),
    
    terms: Yup.array()
    .required("Terms and service must be checked"),
   
   }),

    //submit form
    onSubmit: (values) => {
      router.push({pathname: '/success', query: values});
      console.log("Valid User:", formik.values)
    }
  });
   
  console.log(formik.errors)

  return (
    <div>
      <Head>
        <title>Learn React Form | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   <main className='h-screen flex items-center justify-center'>
    <form 
    onSubmit={formik.handleSubmit}
    className='bg-white flex rounded-lg w-1/2 '>
   
   {/*Left Side */}
    <div className='flex-1 text-gray-700 p-9'>
  <h1 className='text-3xl pb-2 font-semibold'>Let's get started 👋 </h1>
  <p className='text-lg text-gray-500'>
    Join our E-learning platform today and unlock over 500+ courses and digital assets ready to download.
  </p>

  {/*Form Starts here */}
  <div className='mt-6'>
    <div className='pb-2'>
      <label className='block font-bold text-sm pb-2' htmlFor="name">
      Name
      </label>
      <input className='border-2 border-gray-500 p-2 rounded-md w-1/2  focus:border-teal-500 focus:ring-teal-500'
       type="text"
       name="name" 
       value={formik.values.name} 
       onChange={formik.handleChange}
       onBlur={formik.handleBlur}
       placeholder="Enter your name" />   
       </div>
       {
      formik.touched.name && formik.errors.name ?
      <p className='text-red-500 text-sm my-1'>{formik.errors.name}</p>
      : null
    }
       <div className='pb-2'>
      <label className='block font-bold text-sm pb-2' htmlFor="email">Email</label>
      <input className='border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500'
       type="email"
       name="email" 
       value={formik.values.email} 
       onChange={formik.handleChange}
       onBlur={formik.handleBlur}      
       placeholder="Enter your email" />   
       </div>
       {
      formik.touched.email && formik.errors.email ?
      <p className='text-red-500 text-sm my-1'>{formik.errors.email}</p>
      : null
    }
       <div className='pb-2'>
      <label className='block font-bold text-sm pb-2' htmlFor="country">Country</label> 
      <select
      name='country'
      value={formik.values.country} 
      onChange={formik.handleChange}
      className='border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500'>
        <option>India</option>
        <option>United States</option>
        <option>United Kingdom</option>
        <option>Germany</option>
        <option>Normay</option>
      </select>
       </div>
     

       <div className='pb-2'>
      <label className='block font-bold text-sm pb-2' htmlFor="email">Terms of service</label>    
    <div className='flex items-center gap-2 '>
    <input type="checkbox"
     name='terms'
     onChange={formik.handleChange}
     onBlur={formik.handleBlur}
     value='checked' 
     className='h-5 w-5 text-teal-500 border-2 border-gray-500 focus:border-teal-500 focus:ring-teal-500'/>
     </div>
    {
      formik.touched.terms && formik.errors.terms ?
      <p className='text-red-500 text-sm my-1'>{formik.errors.terms}</p>
      : null
    }
       </div>       
  </div>
  <button type='submit' className='bg-teal-500 font-semibold text-sm text-white py-3  mt-6 rounded-lg w-full '>Start learning today!</button>
    </div>

      {/*Right Side */}     
       <div className='relative flex-1'>
      <Image src={formImage} alt='learn-form'  fill className='object-cover rounded-lg' />
       </div>

    </form>
   </main>
    </div>
  )
}
